/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class EndPoint : TBase
{

  public string Ip { get; set; }

  public int Port { get; set; }

  public EndPoint() {
  }

  public EndPoint(string ip, int port) : this() {
    this.Ip = ip;
    this.Port = port;
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_ip = false;
      bool isset_port = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Ip = iprot.ReadString();
              isset_ip = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Port = iprot.ReadI32();
              isset_port = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_ip)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Ip not set");
      if (!isset_port)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Port not set");
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("EndPoint");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Ip == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Ip not set");
      field.Name = "ip";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Ip);
      oprot.WriteFieldEnd();
      field.Name = "port";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Port);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("EndPoint(");
    __sb.Append(", Ip: ");
    __sb.Append(Ip);
    __sb.Append(", Port: ");
    __sb.Append(Port);
    __sb.Append(")");
    return __sb.ToString();
  }

}

