/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class TSFetchResultsReq : TBase
{
  private long _timeout;

  public long SessionId { get; set; }

  public string Statement { get; set; }

  public int FetchSize { get; set; }

  public long QueryId { get; set; }

  public bool IsAlign { get; set; }

  public long Timeout
  {
    get
    {
      return _timeout;
    }
    set
    {
      __isset.timeout = true;
      this._timeout = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool timeout;
  }

  public TSFetchResultsReq() {
  }

  public TSFetchResultsReq(long sessionId, string statement, int fetchSize, long queryId, bool isAlign) : this() {
    this.SessionId = sessionId;
    this.Statement = statement;
    this.FetchSize = fetchSize;
    this.QueryId = queryId;
    this.IsAlign = isAlign;
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_sessionId = false;
      bool isset_statement = false;
      bool isset_fetchSize = false;
      bool isset_queryId = false;
      bool isset_isAlign = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              SessionId = iprot.ReadI64();
              isset_sessionId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Statement = iprot.ReadString();
              isset_statement = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              FetchSize = iprot.ReadI32();
              isset_fetchSize = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I64) {
              QueryId = iprot.ReadI64();
              isset_queryId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Bool) {
              IsAlign = iprot.ReadBool();
              isset_isAlign = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I64) {
              Timeout = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_sessionId)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field SessionId not set");
      if (!isset_statement)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Statement not set");
      if (!isset_fetchSize)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field FetchSize not set");
      if (!isset_queryId)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field QueryId not set");
      if (!isset_isAlign)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field IsAlign not set");
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("TSFetchResultsReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "sessionId";
      field.Type = TType.I64;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(SessionId);
      oprot.WriteFieldEnd();
      if (Statement == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Statement not set");
      field.Name = "statement";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Statement);
      oprot.WriteFieldEnd();
      field.Name = "fetchSize";
      field.Type = TType.I32;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(FetchSize);
      oprot.WriteFieldEnd();
      field.Name = "queryId";
      field.Type = TType.I64;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(QueryId);
      oprot.WriteFieldEnd();
      field.Name = "isAlign";
      field.Type = TType.Bool;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteBool(IsAlign);
      oprot.WriteFieldEnd();
      if (__isset.timeout) {
        field.Name = "timeout";
        field.Type = TType.I64;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Timeout);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("TSFetchResultsReq(");
    __sb.Append(", SessionId: ");
    __sb.Append(SessionId);
    __sb.Append(", Statement: ");
    __sb.Append(Statement);
    __sb.Append(", FetchSize: ");
    __sb.Append(FetchSize);
    __sb.Append(", QueryId: ");
    __sb.Append(QueryId);
    __sb.Append(", IsAlign: ");
    __sb.Append(IsAlign);
    if (__isset.timeout) {
      __sb.Append(", Timeout: ");
      __sb.Append(Timeout);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

