/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class TSInsertRecordsOfOneDeviceReq : TBase
{

  public long SessionId { get; set; }

  public string DeviceId { get; set; }

  public List<List<string>> MeasurementsList { get; set; }

  public List<byte[]> ValuesList { get; set; }

  public List<long> Timestamps { get; set; }

  public TSInsertRecordsOfOneDeviceReq() {
  }

  public TSInsertRecordsOfOneDeviceReq(long sessionId, string deviceId, List<List<string>> measurementsList, List<byte[]> valuesList, List<long> timestamps) : this() {
    this.SessionId = sessionId;
    this.DeviceId = deviceId;
    this.MeasurementsList = measurementsList;
    this.ValuesList = valuesList;
    this.Timestamps = timestamps;
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_sessionId = false;
      bool isset_deviceId = false;
      bool isset_measurementsList = false;
      bool isset_valuesList = false;
      bool isset_timestamps = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              SessionId = iprot.ReadI64();
              isset_sessionId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              DeviceId = iprot.ReadString();
              isset_deviceId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                MeasurementsList = new List<List<string>>();
                TList _list123 = iprot.ReadListBegin();
                for( int _i124 = 0; _i124 < _list123.Count; ++_i124)
                {
                  List<string> _elem125;
                  {
                    _elem125 = new List<string>();
                    TList _list126 = iprot.ReadListBegin();
                    for( int _i127 = 0; _i127 < _list126.Count; ++_i127)
                    {
                      string _elem128;
                      _elem128 = iprot.ReadString();
                      _elem125.Add(_elem128);
                    }
                    iprot.ReadListEnd();
                  }
                  MeasurementsList.Add(_elem125);
                }
                iprot.ReadListEnd();
              }
              isset_measurementsList = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                ValuesList = new List<byte[]>();
                TList _list129 = iprot.ReadListBegin();
                for( int _i130 = 0; _i130 < _list129.Count; ++_i130)
                {
                  byte[] _elem131;
                  _elem131 = iprot.ReadBinary();
                  ValuesList.Add(_elem131);
                }
                iprot.ReadListEnd();
              }
              isset_valuesList = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.List) {
              {
                Timestamps = new List<long>();
                TList _list132 = iprot.ReadListBegin();
                for( int _i133 = 0; _i133 < _list132.Count; ++_i133)
                {
                  long _elem134;
                  _elem134 = iprot.ReadI64();
                  Timestamps.Add(_elem134);
                }
                iprot.ReadListEnd();
              }
              isset_timestamps = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_sessionId)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field SessionId not set");
      if (!isset_deviceId)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field DeviceId not set");
      if (!isset_measurementsList)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field MeasurementsList not set");
      if (!isset_valuesList)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field ValuesList not set");
      if (!isset_timestamps)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Timestamps not set");
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("TSInsertRecordsOfOneDeviceReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "sessionId";
      field.Type = TType.I64;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(SessionId);
      oprot.WriteFieldEnd();
      if (DeviceId == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field DeviceId not set");
      field.Name = "deviceId";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(DeviceId);
      oprot.WriteFieldEnd();
      if (MeasurementsList == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field MeasurementsList not set");
      field.Name = "measurementsList";
      field.Type = TType.List;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.List, MeasurementsList.Count));
        foreach (List<string> _iter135 in MeasurementsList)
        {
          {
            oprot.WriteListBegin(new TList(TType.String, _iter135.Count));
            foreach (string _iter136 in _iter135)
            {
              oprot.WriteString(_iter136);
            }
            oprot.WriteListEnd();
          }
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
      if (ValuesList == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field ValuesList not set");
      field.Name = "valuesList";
      field.Type = TType.List;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.String, ValuesList.Count));
        foreach (byte[] _iter137 in ValuesList)
        {
          oprot.WriteBinary(_iter137);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
      if (Timestamps == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Timestamps not set");
      field.Name = "timestamps";
      field.Type = TType.List;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.I64, Timestamps.Count));
        foreach (long _iter138 in Timestamps)
        {
          oprot.WriteI64(_iter138);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("TSInsertRecordsOfOneDeviceReq(");
    __sb.Append(", SessionId: ");
    __sb.Append(SessionId);
    __sb.Append(", DeviceId: ");
    __sb.Append(DeviceId);
    __sb.Append(", MeasurementsList: ");
    __sb.Append(MeasurementsList);
    __sb.Append(", ValuesList: ");
    __sb.Append(ValuesList);
    __sb.Append(", Timestamps: ");
    __sb.Append(Timestamps);
    __sb.Append(")");
    return __sb.ToString();
  }

}

