/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling


public partial class TSInsertStringRecordsReq : TBase
{

  public long SessionId { get; set; }

  public List<string> DeviceIds { get; set; }

  public List<List<string>> MeasurementsList { get; set; }

  public List<List<string>> ValuesList { get; set; }

  public List<long> Timestamps { get; set; }

  public TSInsertStringRecordsReq()
  {
  }

  public TSInsertStringRecordsReq(long sessionId, List<string> deviceIds, List<List<string>> measurementsList, List<List<string>> valuesList, List<long> timestamps) : this()
  {
    this.SessionId = sessionId;
    this.DeviceIds = deviceIds;
    this.MeasurementsList = measurementsList;
    this.ValuesList = valuesList;
    this.Timestamps = timestamps;
  }

  public TSInsertStringRecordsReq DeepCopy()
  {
    var tmp189 = new TSInsertStringRecordsReq();
    tmp189.SessionId = this.SessionId;
    if((DeviceIds != null))
    {
      tmp189.DeviceIds = this.DeviceIds.DeepCopy();
    }
    if((MeasurementsList != null))
    {
      tmp189.MeasurementsList = this.MeasurementsList.DeepCopy();
    }
    if((ValuesList != null))
    {
      tmp189.ValuesList = this.ValuesList.DeepCopy();
    }
    if((Timestamps != null))
    {
      tmp189.Timestamps = this.Timestamps.DeepCopy();
    }
    return tmp189;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_sessionId = false;
      bool isset_deviceIds = false;
      bool isset_measurementsList = false;
      bool isset_valuesList = false;
      bool isset_timestamps = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64)
            {
              SessionId = await iprot.ReadI64Async(cancellationToken);
              isset_sessionId = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                TList _list190 = await iprot.ReadListBeginAsync(cancellationToken);
                DeviceIds = new List<string>(_list190.Count);
                for(int _i191 = 0; _i191 < _list190.Count; ++_i191)
                {
                  string _elem192;
                  _elem192 = await iprot.ReadStringAsync(cancellationToken);
                  DeviceIds.Add(_elem192);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_deviceIds = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                TList _list193 = await iprot.ReadListBeginAsync(cancellationToken);
                MeasurementsList = new List<List<string>>(_list193.Count);
                for(int _i194 = 0; _i194 < _list193.Count; ++_i194)
                {
                  List<string> _elem195;
                  {
                    TList _list196 = await iprot.ReadListBeginAsync(cancellationToken);
                    _elem195 = new List<string>(_list196.Count);
                    for(int _i197 = 0; _i197 < _list196.Count; ++_i197)
                    {
                      string _elem198;
                      _elem198 = await iprot.ReadStringAsync(cancellationToken);
                      _elem195.Add(_elem198);
                    }
                    await iprot.ReadListEndAsync(cancellationToken);
                  }
                  MeasurementsList.Add(_elem195);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_measurementsList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.List)
            {
              {
                TList _list199 = await iprot.ReadListBeginAsync(cancellationToken);
                ValuesList = new List<List<string>>(_list199.Count);
                for(int _i200 = 0; _i200 < _list199.Count; ++_i200)
                {
                  List<string> _elem201;
                  {
                    TList _list202 = await iprot.ReadListBeginAsync(cancellationToken);
                    _elem201 = new List<string>(_list202.Count);
                    for(int _i203 = 0; _i203 < _list202.Count; ++_i203)
                    {
                      string _elem204;
                      _elem204 = await iprot.ReadStringAsync(cancellationToken);
                      _elem201.Add(_elem204);
                    }
                    await iprot.ReadListEndAsync(cancellationToken);
                  }
                  ValuesList.Add(_elem201);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_valuesList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.List)
            {
              {
                TList _list205 = await iprot.ReadListBeginAsync(cancellationToken);
                Timestamps = new List<long>(_list205.Count);
                for(int _i206 = 0; _i206 < _list205.Count; ++_i206)
                {
                  long _elem207;
                  _elem207 = await iprot.ReadI64Async(cancellationToken);
                  Timestamps.Add(_elem207);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_timestamps = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_sessionId)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_deviceIds)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_measurementsList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_valuesList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_timestamps)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("TSInsertStringRecordsReq");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      field.Name = "sessionId";
      field.Type = TType.I64;
      field.ID = 1;
      await oprot.WriteFieldBeginAsync(field, cancellationToken);
      await oprot.WriteI64Async(SessionId, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if((DeviceIds != null))
      {
        field.Name = "deviceIds";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, DeviceIds.Count), cancellationToken);
          foreach (string _iter208 in DeviceIds)
          {
            await oprot.WriteStringAsync(_iter208, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MeasurementsList != null))
      {
        field.Name = "measurementsList";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.List, MeasurementsList.Count), cancellationToken);
          foreach (List<string> _iter209 in MeasurementsList)
          {
            {
              await oprot.WriteListBeginAsync(new TList(TType.String, _iter209.Count), cancellationToken);
              foreach (string _iter210 in _iter209)
              {
                await oprot.WriteStringAsync(_iter210, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
            }
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((ValuesList != null))
      {
        field.Name = "valuesList";
        field.Type = TType.List;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.List, ValuesList.Count), cancellationToken);
          foreach (List<string> _iter211 in ValuesList)
          {
            {
              await oprot.WriteListBeginAsync(new TList(TType.String, _iter211.Count), cancellationToken);
              foreach (string _iter212 in _iter211)
              {
                await oprot.WriteStringAsync(_iter212, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
            }
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Timestamps != null))
      {
        field.Name = "timestamps";
        field.Type = TType.List;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.I64, Timestamps.Count), cancellationToken);
          foreach (long _iter213 in Timestamps)
          {
            await oprot.WriteI64Async(_iter213, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TSInsertStringRecordsReq other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return System.Object.Equals(SessionId, other.SessionId)
      && TCollections.Equals(DeviceIds, other.DeviceIds)
      && TCollections.Equals(MeasurementsList, other.MeasurementsList)
      && TCollections.Equals(ValuesList, other.ValuesList)
      && TCollections.Equals(Timestamps, other.Timestamps);
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      hashcode = (hashcode * 397) + SessionId.GetHashCode();
      if((DeviceIds != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(DeviceIds);
      }
      if((MeasurementsList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(MeasurementsList);
      }
      if((ValuesList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(ValuesList);
      }
      if((Timestamps != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Timestamps);
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("TSInsertStringRecordsReq(");
    sb.Append(", SessionId: ");
    SessionId.ToString(sb);
    if((DeviceIds != null))
    {
      sb.Append(", DeviceIds: ");
      DeviceIds.ToString(sb);
    }
    if((MeasurementsList != null))
    {
      sb.Append(", MeasurementsList: ");
      MeasurementsList.ToString(sb);
    }
    if((ValuesList != null))
    {
      sb.Append(", ValuesList: ");
      ValuesList.ToString(sb);
    }
    if((Timestamps != null))
    {
      sb.Append(", Timestamps: ");
      Timestamps.ToString(sb);
    }
    sb.Append(')');
    return sb.ToString();
  }
}

