/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum TSProtocolVersion
{
  IOTDB_SERVICE_PROTOCOL_V1 = 0,
  IOTDB_SERVICE_PROTOCOL_V2 = 1,
  IOTDB_SERVICE_PROTOCOL_V3 = 2,
}
