/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

public static class rpcExtensions
{
  public static bool Equals(this Dictionary<string, int> instance, object that)
  {
    if (!(that is Dictionary<string, int> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this Dictionary<string, int> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static Dictionary<string, int> DeepCopy(this Dictionary<string, int> source)
  {
    if (source == null)
      return null;

    var tmp447 = new Dictionary<string, int>(source.Count);
    foreach (var pair in source)
      tmp447.Add((pair.Key != null) ? pair.Key : null, pair.Value);
    return tmp447;
  }


  public static bool Equals(this Dictionary<string, string> instance, object that)
  {
    if (!(that is Dictionary<string, string> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this Dictionary<string, string> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static Dictionary<string, string> DeepCopy(this Dictionary<string, string> source)
  {
    if (source == null)
      return null;

    var tmp448 = new Dictionary<string, string>(source.Count);
    foreach (var pair in source)
      tmp448.Add((pair.Key != null) ? pair.Key : null, (pair.Value != null) ? pair.Value : null);
    return tmp448;
  }


  public static bool Equals(this List<Dictionary<string, string>> instance, object that)
  {
    if (!(that is List<Dictionary<string, string>> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<Dictionary<string, string>> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<Dictionary<string, string>> DeepCopy(this List<Dictionary<string, string>> source)
  {
    if (source == null)
      return null;

    var tmp449 = new List<Dictionary<string, string>>(source.Count);
    foreach (var elem in source)
      tmp449.Add((elem != null) ? elem.DeepCopy() : null);
    return tmp449;
  }


  public static bool Equals(this List<List<int>> instance, object that)
  {
    if (!(that is List<List<int>> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<List<int>> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<List<int>> DeepCopy(this List<List<int>> source)
  {
    if (source == null)
      return null;

    var tmp450 = new List<List<int>>(source.Count);
    foreach (var elem in source)
      tmp450.Add((elem != null) ? elem.DeepCopy() : null);
    return tmp450;
  }


  public static bool Equals(this List<List<string>> instance, object that)
  {
    if (!(that is List<List<string>> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<List<string>> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<List<string>> DeepCopy(this List<List<string>> source)
  {
    if (source == null)
      return null;

    var tmp451 = new List<List<string>>(source.Count);
    foreach (var elem in source)
      tmp451.Add((elem != null) ? elem.DeepCopy() : null);
    return tmp451;
  }


  public static bool Equals(this List<TSStatus> instance, object that)
  {
    if (!(that is List<TSStatus> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<TSStatus> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<TSStatus> DeepCopy(this List<TSStatus> source)
  {
    if (source == null)
      return null;

    var tmp452 = new List<TSStatus>(source.Count);
    foreach (var elem in source)
      tmp452.Add((elem != null) ? elem.DeepCopy() : null);
    return tmp452;
  }


  public static bool Equals(this List<byte[]> instance, object that)
  {
    if (!(that is List<byte[]> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<byte[]> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<byte[]> DeepCopy(this List<byte[]> source)
  {
    if (source == null)
      return null;

    var tmp453 = new List<byte[]>(source.Count);
    foreach (var elem in source)
      tmp453.Add((elem != null) ? elem.ToArray() : null);
    return tmp453;
  }


  public static bool Equals(this List<int> instance, object that)
  {
    if (!(that is List<int> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<int> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<int> DeepCopy(this List<int> source)
  {
    if (source == null)
      return null;

    var tmp454 = new List<int>(source.Count);
    foreach (var elem in source)
      tmp454.Add(elem);
    return tmp454;
  }


  public static bool Equals(this List<long> instance, object that)
  {
    if (!(that is List<long> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<long> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<long> DeepCopy(this List<long> source)
  {
    if (source == null)
      return null;

    var tmp455 = new List<long>(source.Count);
    foreach (var elem in source)
      tmp455.Add(elem);
    return tmp455;
  }


  public static bool Equals(this List<string> instance, object that)
  {
    if (!(that is List<string> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<string> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<string> DeepCopy(this List<string> source)
  {
    if (source == null)
      return null;

    var tmp456 = new List<string>(source.Count);
    foreach (var elem in source)
      tmp456.Add((elem != null) ? elem : null);
    return tmp456;
  }


}
