/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling


public partial class TSInsertStringRecordsReq : TBase
{
  private bool _isAligned;

  public long SessionId { get; set; }

  public List<string> PrefixPaths { get; set; }

  public List<List<string>> MeasurementsList { get; set; }

  public List<List<string>> ValuesList { get; set; }

  public List<long> Timestamps { get; set; }

  public bool IsAligned
  {
    get
    {
      return _isAligned;
    }
    set
    {
      __isset.isAligned = true;
      this._isAligned = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool isAligned;
  }

  public TSInsertStringRecordsReq()
  {
  }

  public TSInsertStringRecordsReq(long sessionId, List<string> prefixPaths, List<List<string>> measurementsList, List<List<string>> valuesList, List<long> timestamps) : this()
  {
    this.SessionId = sessionId;
    this.PrefixPaths = prefixPaths;
    this.MeasurementsList = measurementsList;
    this.ValuesList = valuesList;
    this.Timestamps = timestamps;
  }

  public TSInsertStringRecordsReq DeepCopy()
  {
    var tmp229 = new TSInsertStringRecordsReq();
    tmp229.SessionId = this.SessionId;
    if((PrefixPaths != null))
    {
      tmp229.PrefixPaths = this.PrefixPaths.DeepCopy();
    }
    if((MeasurementsList != null))
    {
      tmp229.MeasurementsList = this.MeasurementsList.DeepCopy();
    }
    if((ValuesList != null))
    {
      tmp229.ValuesList = this.ValuesList.DeepCopy();
    }
    if((Timestamps != null))
    {
      tmp229.Timestamps = this.Timestamps.DeepCopy();
    }
    if(__isset.isAligned)
    {
      tmp229.IsAligned = this.IsAligned;
    }
    tmp229.__isset.isAligned = this.__isset.isAligned;
    return tmp229;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_sessionId = false;
      bool isset_prefixPaths = false;
      bool isset_measurementsList = false;
      bool isset_valuesList = false;
      bool isset_timestamps = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64)
            {
              SessionId = await iprot.ReadI64Async(cancellationToken);
              isset_sessionId = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                TList _list230 = await iprot.ReadListBeginAsync(cancellationToken);
                PrefixPaths = new List<string>(_list230.Count);
                for(int _i231 = 0; _i231 < _list230.Count; ++_i231)
                {
                  string _elem232;
                  _elem232 = await iprot.ReadStringAsync(cancellationToken);
                  PrefixPaths.Add(_elem232);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_prefixPaths = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                TList _list233 = await iprot.ReadListBeginAsync(cancellationToken);
                MeasurementsList = new List<List<string>>(_list233.Count);
                for(int _i234 = 0; _i234 < _list233.Count; ++_i234)
                {
                  List<string> _elem235;
                  {
                    TList _list236 = await iprot.ReadListBeginAsync(cancellationToken);
                    _elem235 = new List<string>(_list236.Count);
                    for(int _i237 = 0; _i237 < _list236.Count; ++_i237)
                    {
                      string _elem238;
                      _elem238 = await iprot.ReadStringAsync(cancellationToken);
                      _elem235.Add(_elem238);
                    }
                    await iprot.ReadListEndAsync(cancellationToken);
                  }
                  MeasurementsList.Add(_elem235);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_measurementsList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.List)
            {
              {
                TList _list239 = await iprot.ReadListBeginAsync(cancellationToken);
                ValuesList = new List<List<string>>(_list239.Count);
                for(int _i240 = 0; _i240 < _list239.Count; ++_i240)
                {
                  List<string> _elem241;
                  {
                    TList _list242 = await iprot.ReadListBeginAsync(cancellationToken);
                    _elem241 = new List<string>(_list242.Count);
                    for(int _i243 = 0; _i243 < _list242.Count; ++_i243)
                    {
                      string _elem244;
                      _elem244 = await iprot.ReadStringAsync(cancellationToken);
                      _elem241.Add(_elem244);
                    }
                    await iprot.ReadListEndAsync(cancellationToken);
                  }
                  ValuesList.Add(_elem241);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_valuesList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.List)
            {
              {
                TList _list245 = await iprot.ReadListBeginAsync(cancellationToken);
                Timestamps = new List<long>(_list245.Count);
                for(int _i246 = 0; _i246 < _list245.Count; ++_i246)
                {
                  long _elem247;
                  _elem247 = await iprot.ReadI64Async(cancellationToken);
                  Timestamps.Add(_elem247);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_timestamps = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.Bool)
            {
              IsAligned = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_sessionId)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_prefixPaths)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_measurementsList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_valuesList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_timestamps)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("TSInsertStringRecordsReq");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      field.Name = "sessionId";
      field.Type = TType.I64;
      field.ID = 1;
      await oprot.WriteFieldBeginAsync(field, cancellationToken);
      await oprot.WriteI64Async(SessionId, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if((PrefixPaths != null))
      {
        field.Name = "prefixPaths";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, PrefixPaths.Count), cancellationToken);
          foreach (string _iter248 in PrefixPaths)
          {
            await oprot.WriteStringAsync(_iter248, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MeasurementsList != null))
      {
        field.Name = "measurementsList";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.List, MeasurementsList.Count), cancellationToken);
          foreach (List<string> _iter249 in MeasurementsList)
          {
            {
              await oprot.WriteListBeginAsync(new TList(TType.String, _iter249.Count), cancellationToken);
              foreach (string _iter250 in _iter249)
              {
                await oprot.WriteStringAsync(_iter250, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
            }
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((ValuesList != null))
      {
        field.Name = "valuesList";
        field.Type = TType.List;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.List, ValuesList.Count), cancellationToken);
          foreach (List<string> _iter251 in ValuesList)
          {
            {
              await oprot.WriteListBeginAsync(new TList(TType.String, _iter251.Count), cancellationToken);
              foreach (string _iter252 in _iter251)
              {
                await oprot.WriteStringAsync(_iter252, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
            }
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Timestamps != null))
      {
        field.Name = "timestamps";
        field.Type = TType.List;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.I64, Timestamps.Count), cancellationToken);
          foreach (long _iter253 in Timestamps)
          {
            await oprot.WriteI64Async(_iter253, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.isAligned)
      {
        field.Name = "isAligned";
        field.Type = TType.Bool;
        field.ID = 6;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteBoolAsync(IsAligned, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TSInsertStringRecordsReq other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return System.Object.Equals(SessionId, other.SessionId)
      && TCollections.Equals(PrefixPaths, other.PrefixPaths)
      && TCollections.Equals(MeasurementsList, other.MeasurementsList)
      && TCollections.Equals(ValuesList, other.ValuesList)
      && TCollections.Equals(Timestamps, other.Timestamps)
      && ((__isset.isAligned == other.__isset.isAligned) && ((!__isset.isAligned) || (System.Object.Equals(IsAligned, other.IsAligned))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      hashcode = (hashcode * 397) + SessionId.GetHashCode();
      if((PrefixPaths != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(PrefixPaths);
      }
      if((MeasurementsList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(MeasurementsList);
      }
      if((ValuesList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(ValuesList);
      }
      if((Timestamps != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Timestamps);
      }
      if(__isset.isAligned)
      {
        hashcode = (hashcode * 397) + IsAligned.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("TSInsertStringRecordsReq(");
    sb.Append(", SessionId: ");
    SessionId.ToString(sb);
    if((PrefixPaths != null))
    {
      sb.Append(", PrefixPaths: ");
      PrefixPaths.ToString(sb);
    }
    if((MeasurementsList != null))
    {
      sb.Append(", MeasurementsList: ");
      MeasurementsList.ToString(sb);
    }
    if((ValuesList != null))
    {
      sb.Append(", ValuesList: ");
      ValuesList.ToString(sb);
    }
    if((Timestamps != null))
    {
      sb.Append(", Timestamps: ");
      Timestamps.ToString(sb);
    }
    if(__isset.isAligned)
    {
      sb.Append(", IsAligned: ");
      IsAligned.ToString(sb);
    }
    sb.Append(')');
    return sb.ToString();
  }
}

