/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling


public partial class TSInsertTabletsReq : TBase
{
  private bool _isAligned;

  public long SessionId { get; set; }

  public List<string> PrefixPaths { get; set; }

  public List<List<string>> MeasurementsList { get; set; }

  public List<byte[]> ValuesList { get; set; }

  public List<byte[]> TimestampsList { get; set; }

  public List<List<int>> TypesList { get; set; }

  public List<int> SizeList { get; set; }

  public bool IsAligned
  {
    get
    {
      return _isAligned;
    }
    set
    {
      __isset.isAligned = true;
      this._isAligned = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool isAligned;
  }

  public TSInsertTabletsReq()
  {
  }

  public TSInsertTabletsReq(long sessionId, List<string> prefixPaths, List<List<string>> measurementsList, List<byte[]> valuesList, List<byte[]> timestampsList, List<List<int>> typesList, List<int> sizeList) : this()
  {
    this.SessionId = sessionId;
    this.PrefixPaths = prefixPaths;
    this.MeasurementsList = measurementsList;
    this.ValuesList = valuesList;
    this.TimestampsList = timestampsList;
    this.TypesList = typesList;
    this.SizeList = sizeList;
  }

  public TSInsertTabletsReq DeepCopy()
  {
    var tmp133 = new TSInsertTabletsReq();
    tmp133.SessionId = this.SessionId;
    if((PrefixPaths != null))
    {
      tmp133.PrefixPaths = this.PrefixPaths.DeepCopy();
    }
    if((MeasurementsList != null))
    {
      tmp133.MeasurementsList = this.MeasurementsList.DeepCopy();
    }
    if((ValuesList != null))
    {
      tmp133.ValuesList = this.ValuesList.DeepCopy();
    }
    if((TimestampsList != null))
    {
      tmp133.TimestampsList = this.TimestampsList.DeepCopy();
    }
    if((TypesList != null))
    {
      tmp133.TypesList = this.TypesList.DeepCopy();
    }
    if((SizeList != null))
    {
      tmp133.SizeList = this.SizeList.DeepCopy();
    }
    if(__isset.isAligned)
    {
      tmp133.IsAligned = this.IsAligned;
    }
    tmp133.__isset.isAligned = this.__isset.isAligned;
    return tmp133;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_sessionId = false;
      bool isset_prefixPaths = false;
      bool isset_measurementsList = false;
      bool isset_valuesList = false;
      bool isset_timestampsList = false;
      bool isset_typesList = false;
      bool isset_sizeList = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64)
            {
              SessionId = await iprot.ReadI64Async(cancellationToken);
              isset_sessionId = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                TList _list134 = await iprot.ReadListBeginAsync(cancellationToken);
                PrefixPaths = new List<string>(_list134.Count);
                for(int _i135 = 0; _i135 < _list134.Count; ++_i135)
                {
                  string _elem136;
                  _elem136 = await iprot.ReadStringAsync(cancellationToken);
                  PrefixPaths.Add(_elem136);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_prefixPaths = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                TList _list137 = await iprot.ReadListBeginAsync(cancellationToken);
                MeasurementsList = new List<List<string>>(_list137.Count);
                for(int _i138 = 0; _i138 < _list137.Count; ++_i138)
                {
                  List<string> _elem139;
                  {
                    TList _list140 = await iprot.ReadListBeginAsync(cancellationToken);
                    _elem139 = new List<string>(_list140.Count);
                    for(int _i141 = 0; _i141 < _list140.Count; ++_i141)
                    {
                      string _elem142;
                      _elem142 = await iprot.ReadStringAsync(cancellationToken);
                      _elem139.Add(_elem142);
                    }
                    await iprot.ReadListEndAsync(cancellationToken);
                  }
                  MeasurementsList.Add(_elem139);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_measurementsList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.List)
            {
              {
                TList _list143 = await iprot.ReadListBeginAsync(cancellationToken);
                ValuesList = new List<byte[]>(_list143.Count);
                for(int _i144 = 0; _i144 < _list143.Count; ++_i144)
                {
                  byte[] _elem145;
                  _elem145 = await iprot.ReadBinaryAsync(cancellationToken);
                  ValuesList.Add(_elem145);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_valuesList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.List)
            {
              {
                TList _list146 = await iprot.ReadListBeginAsync(cancellationToken);
                TimestampsList = new List<byte[]>(_list146.Count);
                for(int _i147 = 0; _i147 < _list146.Count; ++_i147)
                {
                  byte[] _elem148;
                  _elem148 = await iprot.ReadBinaryAsync(cancellationToken);
                  TimestampsList.Add(_elem148);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_timestampsList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.List)
            {
              {
                TList _list149 = await iprot.ReadListBeginAsync(cancellationToken);
                TypesList = new List<List<int>>(_list149.Count);
                for(int _i150 = 0; _i150 < _list149.Count; ++_i150)
                {
                  List<int> _elem151;
                  {
                    TList _list152 = await iprot.ReadListBeginAsync(cancellationToken);
                    _elem151 = new List<int>(_list152.Count);
                    for(int _i153 = 0; _i153 < _list152.Count; ++_i153)
                    {
                      int _elem154;
                      _elem154 = await iprot.ReadI32Async(cancellationToken);
                      _elem151.Add(_elem154);
                    }
                    await iprot.ReadListEndAsync(cancellationToken);
                  }
                  TypesList.Add(_elem151);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_typesList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.List)
            {
              {
                TList _list155 = await iprot.ReadListBeginAsync(cancellationToken);
                SizeList = new List<int>(_list155.Count);
                for(int _i156 = 0; _i156 < _list155.Count; ++_i156)
                {
                  int _elem157;
                  _elem157 = await iprot.ReadI32Async(cancellationToken);
                  SizeList.Add(_elem157);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
              isset_sizeList = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.Bool)
            {
              IsAligned = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_sessionId)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_prefixPaths)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_measurementsList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_valuesList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_timestampsList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_typesList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_sizeList)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("TSInsertTabletsReq");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      field.Name = "sessionId";
      field.Type = TType.I64;
      field.ID = 1;
      await oprot.WriteFieldBeginAsync(field, cancellationToken);
      await oprot.WriteI64Async(SessionId, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if((PrefixPaths != null))
      {
        field.Name = "prefixPaths";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, PrefixPaths.Count), cancellationToken);
          foreach (string _iter158 in PrefixPaths)
          {
            await oprot.WriteStringAsync(_iter158, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MeasurementsList != null))
      {
        field.Name = "measurementsList";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.List, MeasurementsList.Count), cancellationToken);
          foreach (List<string> _iter159 in MeasurementsList)
          {
            {
              await oprot.WriteListBeginAsync(new TList(TType.String, _iter159.Count), cancellationToken);
              foreach (string _iter160 in _iter159)
              {
                await oprot.WriteStringAsync(_iter160, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
            }
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((ValuesList != null))
      {
        field.Name = "valuesList";
        field.Type = TType.List;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, ValuesList.Count), cancellationToken);
          foreach (byte[] _iter161 in ValuesList)
          {
            await oprot.WriteBinaryAsync(_iter161, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TimestampsList != null))
      {
        field.Name = "timestampsList";
        field.Type = TType.List;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, TimestampsList.Count), cancellationToken);
          foreach (byte[] _iter162 in TimestampsList)
          {
            await oprot.WriteBinaryAsync(_iter162, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TypesList != null))
      {
        field.Name = "typesList";
        field.Type = TType.List;
        field.ID = 6;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.List, TypesList.Count), cancellationToken);
          foreach (List<int> _iter163 in TypesList)
          {
            {
              await oprot.WriteListBeginAsync(new TList(TType.I32, _iter163.Count), cancellationToken);
              foreach (int _iter164 in _iter163)
              {
                await oprot.WriteI32Async(_iter164, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
            }
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((SizeList != null))
      {
        field.Name = "sizeList";
        field.Type = TType.List;
        field.ID = 7;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.I32, SizeList.Count), cancellationToken);
          foreach (int _iter165 in SizeList)
          {
            await oprot.WriteI32Async(_iter165, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.isAligned)
      {
        field.Name = "isAligned";
        field.Type = TType.Bool;
        field.ID = 8;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteBoolAsync(IsAligned, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is TSInsertTabletsReq other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return System.Object.Equals(SessionId, other.SessionId)
      && TCollections.Equals(PrefixPaths, other.PrefixPaths)
      && TCollections.Equals(MeasurementsList, other.MeasurementsList)
      && TCollections.Equals(ValuesList, other.ValuesList)
      && TCollections.Equals(TimestampsList, other.TimestampsList)
      && TCollections.Equals(TypesList, other.TypesList)
      && TCollections.Equals(SizeList, other.SizeList)
      && ((__isset.isAligned == other.__isset.isAligned) && ((!__isset.isAligned) || (System.Object.Equals(IsAligned, other.IsAligned))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      hashcode = (hashcode * 397) + SessionId.GetHashCode();
      if((PrefixPaths != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(PrefixPaths);
      }
      if((MeasurementsList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(MeasurementsList);
      }
      if((ValuesList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(ValuesList);
      }
      if((TimestampsList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(TimestampsList);
      }
      if((TypesList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(TypesList);
      }
      if((SizeList != null))
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(SizeList);
      }
      if(__isset.isAligned)
      {
        hashcode = (hashcode * 397) + IsAligned.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("TSInsertTabletsReq(");
    sb.Append(", SessionId: ");
    SessionId.ToString(sb);
    if((PrefixPaths != null))
    {
      sb.Append(", PrefixPaths: ");
      PrefixPaths.ToString(sb);
    }
    if((MeasurementsList != null))
    {
      sb.Append(", MeasurementsList: ");
      MeasurementsList.ToString(sb);
    }
    if((ValuesList != null))
    {
      sb.Append(", ValuesList: ");
      ValuesList.ToString(sb);
    }
    if((TimestampsList != null))
    {
      sb.Append(", TimestampsList: ");
      TimestampsList.ToString(sb);
    }
    if((TypesList != null))
    {
      sb.Append(", TypesList: ");
      TypesList.ToString(sb);
    }
    if((SizeList != null))
    {
      sb.Append(", SizeList: ");
      SizeList.ToString(sb);
    }
    if(__isset.isAligned)
    {
      sb.Append(", IsAligned: ");
      IsAligned.ToString(sb);
    }
    sb.Append(')');
    return sb.ToString();
  }
}

